### ISSUE TITLE
z-ordering of nodes

### ISSUE THREAD

**Issue by dcnieho** [richardpl/lavfi-preview#3]
See this screen shot:
![image](https://user-images.githubusercontent.com/1787673/198994975-a7c16fc3-f31a-4563-b09e-27f8acae4cf8.png)

To repro:
1. make movie src
2. make buffersink
3. click options of movie

This is really two issues:
1. You note that that buffersink node retains focus, not the movie node i just clicked the options button for
2. there is some z-ordering issue here. Even though buffersink is topmost and has focus, some of the elements of the movie src (the text input boxes) are drawn on top over it

**Comment by richardpl** [comment]
This is imnodes bug, looking for alternative imgui node handling lib.

**Comment by dcnieho** [comment]
Hmm, imnodes is kinda the big player for this though, correct? Perhaps better to report the bug to them? Its just a cosmetic issue, your work is still completely usable :)

**Comment by richardpl** [comment]
Looks both issues are resolved now.
