### ISSUE TITLE
remove-button issue

### ISSUE THREAD

**Issue by coderofsalvation** [richardpl/lavfi-preview#8]
cool project, 
Btw. when pressing 'remove' on a movie-source (after clicking options), the application stops on linux:

```
$ ./lavfi-preview-linux64 `
lavfi-preview-linux64: imnodes/imnodes.cpp:470: void ImNodes::{anonymous}::DrawListActivateNodeBackground(int): Assertion `submission_idx != -1' failed.
Aborted (core dumped)
```

**Comment by richardpl** [comment]
Can not reproduce here, what you did exactly step by step?

**Comment by richardpl** [comment]
Should be fixed. "Remove" button was completely removed as it was not cleaning behind correctly. X key still works for removal and should not cause crashes.
