### ISSUE TITLE
swap filename/format order

### ISSUE THREAD

**Issue by coderofsalvation** [richardpl/lavfi-preview#9]
it seems that the movie-node has a hard time loading webcam/x11grab.
How to reproduce:

1. create movie node
1. enter filename `/dev/video0` and format `v4l2` or `video4linux2` (see [docs](https://trac.ffmpeg.org/wiki/Capture/Webcam))
1. enter filename `:0.0+100,200` format `x11grab` (see [docs](https://trac.ffmpeg.org/wiki/Capture/Desktop))

> Usually hitting ctl+enter makes the output-socket appear, but here it displays error:

``` 
Failed to av_format_open_input <filename>
cannot init str for filter
```

looking at the docs, the fileformat should be passed to ffmpeg first, before passing the inputfile..perhaps that's happening in the reversed order?

**Comment by richardpl** [comment]
It does not work as libavdevice is not linked into binary at all currently.
